apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: {{ .Values.flask.port }}
      targetPort: {{ .Values.flask.port }}
      nodePort: {{ .Values.flask.nodePort }}
